language: node_js
node_js: 
  - "9"
dist: trusty
sudo: required

before_script:
  - npm install -g @angular/cli

script:
- ng build --prod --base-href="/mango-ui/" --deploy-url="/mango-ui/"
- cp dist/mango-ui/index.html dist/mango-ui/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/mango-ui
  on:
    branch: master